module.exports = [
    {
        orientation: "@orientation",
        orientationType: "@orientationRight",
        orientationChoice: "@orientationChoiceRight",
        orientationChoiceString: "Right Handed",
        body: "@body",
        bodyType: "@bodySilverburst",
        bodyChoice: "@bodyChoiceSilverburst",
        bodyChoiceString: "Silverburst",
        neckShape: "@neckShape",
        neckShapeType: "@neckShapeAmericanPro",
        neckShapeChoice: "@neckShapeChoiceAP",
        neckShapeChoiceString: "American Professional",
        fingerboard: "@fingerboard",
        fingerboardType: "@fingerboardMaple",
        fingerboardChoice: "@fingerboardChoiceMaple",
        fingerboardChoiceString: "Maple",
        pickguard: "@pickguard",
        pickguardType: "@pickguard4PlyAgedWhitePearl",
        pickguardChoice: "@pickguardChoice4PlyAgedWhitePearl",
        pickguardChoiceString: "4 Ply Aged White Pearl",
        pickups: "@pickups",
        pickupsType: "@pickupsNoiseless",
        pickupsChoice: "@pickupsChoiceNoiseless",
        pickupsChoiceString: "4th Gen Noiseless",
        tuningMachines: "@tuningMachines",
        tuningMachinesType: "@tuningMachinesAmericanProfessional",
        tuningMachinesChoice: "@tuningMachinesChoiceAP",
        tuningMachinesChoiceString: "American Professional",
        bridge: "@bridge",
        bridgeType: "@bridgeAmericanPB",
        bridgeChoice: "@bridgeChoiceAPB",
        bridgeChoiceString: "American Professional Bass",
        strings: "@strings",
        stringsType: "@stringsGauge45101",
        stringsChoice: "@stringsChoiceGauge45101",
        stringsChoiceString: "0.045-0.105",
        caseAndPackaging: "@caseAndPackaging",
        caseAndPackagingType: "@caseAndPackagingJazzBassProRight",
        caseAndPackagingChoice: "@caseAndPackagingChoiceJazzBassProRight",
        caseAndPackagingChoiceString: "JazzBass-Pro Case & Packaging-Right",
        addToCart: "@addToCart",
        reset: "@reset",
        closeResetPopUp: "@closeResetPopUp"
    }
]