module.exports = [
    {
        orientation: "@orientation",
        orientationType: "@orientationRight",
        orientationChoice: "@orientationChoiceRight",
        orientationChoiceString: "Right Handed",
        body: "@body",
        bodyType: "@bodyIncaSilver",
        bodyChoice: "@bodyChoiceIncaSilver",
        bodyChoiceString: "Inca Silver",
        neckShape: "@neckShape",
        neckShapeType: "@neckShapeAmericanPro",
        neckShapeChoice: "@neckShapeChoiceAP",
        neckShapeChoiceString: "American Professional",
        fingerboard: "@fingerboard",
        fingerboardType: "@fingerboardMaple",
        fingerboardChoice: "@fingerboardChoiceMaple",
        fingerboardChoiceString: "Maple",
        pickguard: "@pickguard",
        pickguardType: "@pickguard3PlyParchment",
        pickguardChoice: "@pickguardChoice3PlyParchment",
        pickguardChoiceString: "3 Ply Parchment",
        pickups: "@pickups",
        pickupsType: "@pickupsNoiseless",
        pickupsChoice: "@pickupsChoiceNoiseless",
        pickupsChoiceString: "4th Gen Noiseless",
        tuningMachines: "@tuningMachines",
        tuningMachinesType: "@tuningMachinesAmericanProfessional",
        tuningMachinesChoice: "@tuningMachinesChoiceAP",
        tuningMachinesChoiceString: "American Professional",
        bridge: "@bridge",
        bridgeType: "@bridgeAmericanPB",
        bridgeChoice: "@bridgeChoiceAPB",
        bridgeChoiceString: "American Professional Bass",
        strings: "@strings",
        stringsType: "@stringsGauge45101",
        stringsChoice: "@stringsChoiceGauge45101",
        stringsChoiceString: "0.045-0.105",
        caseAndPackaging: "@caseAndPackaging",
        caseAndPackagingType: "@caseAndPackagingJazzBassProRight",
        caseAndPackagingChoice: "@caseAndPackagingChoiceJazzBassProRight",
        caseAndPackagingChoiceString: "JazzBass-Pro Case & Packaging-Right",
        addToCart: "@addToCart",
        reset: "@reset",
        closeResetPopUp: "@closeResetPopUp"
    },
    {
        orientation: "@orientation",
        orientationType: "@orientationLeft",
        orientationChoice: "@orientationChoiceLeft",
        orientationChoiceString: "Left Handed",
        body: "@body",
        bodyType: "@bodyMysticSeafoamGreen",
        bodyChoice: "@bodyChoiceMysticSeafoamGreen",
        bodyChoiceString: "Mystic Seafoam Green",
        neckShape: "@neckShape",
        neckShapeType: "@neckShapeAmericanPro",
        neckShapeChoice: "@neckShapeChoiceAP",
        neckShapeChoiceString: "American Professional",
        fingerboard: "@fingerboard",
        fingerboardType: "@fingerboardMaple",
        fingerboardChoice: "@fingerboardChoiceMaple",
        fingerboardChoiceString: "Maple",
        pickguard: "@pickguard",
        pickguardType: "@pickguard3PlyMintGreen",
        pickguardChoice: "@pickguardChoice3PlyMintGreen",
        pickguardChoiceString: "3 Ply Mint Green",
        pickups: "@pickups",
        pickupsType: "@pickupsPureVintage64JB",
        pickupsChoice: "@pickupsChoicePureVintage64JB",
        pickupsChoiceString: "Pure Vintage '64 Jazz Bass",
        tuningMachines: "@tuningMachines",
        tuningMachinesType: "@tuningMachinesAmericanProfessional",
        tuningMachinesChoice: "@tuningMachinesChoiceAP",
        tuningMachinesChoiceString: "American Professional",
        bridge: "@bridge",
        bridgeType: "@bridgeAmericanPB",
        bridgeChoice: "@bridgeChoiceAPB",
        bridgeChoiceString: "American Professional Bass",
        strings: "@strings",
        stringsType: "@stringsGauge45101",
        stringsChoice: "@stringsChoiceGauge45101",
        stringsChoiceString: "0.045-0.105",
        caseAndPackaging: "@caseAndPackaging",
        caseAndPackagingType: "@caseAndPackagingJazzBassProLeft",
        caseAndPackagingChoice: "@caseAndPackagingChoiceJazzBassProLeft",
        caseAndPackagingChoiceString: "JazzBass-Pro Case & Packaging-Left",
        addToCart: "@addToCart",
        reset: "@reset",
        closeResetPopUp: "@closeResetPopUp"
    }  
]